name: Create Pull Request for back-merge

on:
  push:
    branches:
      - 'main'

jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-20.04

    steps:
      - name: Execute Pull Request Create command
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'refs/heads/main',
              base: 'refs/heads/develop',
              title: 'Automated back-merge to develop from the main branch',
              body: 'An automated pull request created for the intent of performing a back-merge from main to develop',
              draft: false,
            });

